services:
  - type: web
    name: prepboat-backend
    env: docker
    plan: free
    rootDir: backend
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres.hpdixybgdurhrxgusjls:Shivaji%402006%23@aws-1-ap-south-1.pooler.supabase.com:6543/postgres
      - key: GEMINI_API_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "1440"
