services:
  - type: web
    name: prepboat-backend
    env: docker
    plan: free
    rootDir: backend
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "1440"
